package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/NotHarshhaa/aws-ghost/internal/aws"
	"github.com/NotHarshhaa/aws-ghost/internal/scanner"
	"github.com/NotHarshhaa/aws-ghost/internal/security"
	"github.com/NotHarshhaa/aws-ghost/pkg/types"
	"github.com/spf13/cobra"
)

var (
	terraformOutput string
	terraformFile   string
	includeState    bool
)

var terraformCmd = &cobra.Command{
	Use:   "terraform",
	Short: "Generate Terraform destroy plan for ghost resources",
	Long:  `Export ghost resources as Terraform configuration for controlled cleanup.`,
	RunE:  runTerraform,
}

func init() {
	terraformCmd.Flags().StringVarP(&terraformOutput, "output", "o", "", "Output file path (default: stdout)")
	terraformCmd.Flags().StringVar(&terraformFile, "file", "ghost-destroy.tf", "Default output filename")
	terraformCmd.Flags().BoolVar(&includeState, "include-state", false, "Include terraform state import commands")
}

func runTerraform(cmd *cobra.Command, args []string) error {
	client, err := aws.NewClient(profile, region)
	if err != nil {
		return fmt.Errorf("failed to create AWS client: %w", err)
	}

	secConfig := types.GetSecurityConfig(types.SecurityLevelMedium)
	validator := security.NewValidator(secConfig, client.Config)

	credInfo, err := validator.ValidateCredentials(cmd.Context())
	if err != nil {
		return fmt.Errorf("security validation failed: %w", err)
	}

	registry := scanner.NewRegistry(client)
	scanners := registry.GetFiltered(nil, nil)

	var allResources []types.Resource
	for name, scn := range scanners {
		config := types.ScanConfig{
			Region:   region,
			Profile:  profile,
			IdleDays: idleDays,
			MinCost:  minCost,
		}

		resources, err := scn.Scan(config)
		if err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "Warning: failed to scan %s: %v\n", name, err)
			continue
		}

		allResources = append(allResources, resources...)
	}

	// Generate Terraform configuration
	terraformConfig := generateTerraformConfig(allResources, credInfo.AccountID, region)

	output := terraformConfig
	if includeState {
		output += generateStateImportCommands(allResources)
	}

	if terraformOutput == "" {
		terraformOutput = terraformFile
	}

	if terraformOutput != "" {
		if err := writeToFile(terraformOutput, output); err != nil {
			return fmt.Errorf("failed to write terraform file: %w", err)
		}
		fmt.Printf("✅ Terraform configuration written to: %s\n", terraformOutput)
		fmt.Printf("\n⚠️  IMPORTANT:\n")
		fmt.Printf("  1. Review the generated terraform file carefully\n")
		fmt.Printf("  2. Run 'terraform init' to initialize\n")
		fmt.Printf("  3. Run 'terraform plan' to see what will be destroyed\n")
		fmt.Printf("  4. Run 'terraform apply' to destroy the resources\n")
		if includeState {
			fmt.Printf("  5. Run the state import commands if needed\n")
		}
	} else {
		fmt.Println(output)
	}

	return nil
}

func generateTerraformConfig(resources []types.Resource, accountID, region string) string {
	var sb strings.Builder

	sb.WriteString(`# Terraform configuration to destroy ghost resources
# Generated by aws-ghost v2.1.0
# Account: ` + accountID + `
# Region: ` + region + `
# 
# WARNING: This will destroy the listed resources!
# Review carefully before running terraform apply.

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "` + region + `"
}

`)

	// Group resources by type
	resourcesByType := make(map[string][]types.Resource)
	for _, r := range resources {
		resourcesByType[r.Type] = append(resourcesByType[r.Type], r)
	}

	// Generate EBS volumes
	if vols, ok := resourcesByType["ebs"]; ok && len(vols) > 0 {
		sb.WriteString("# Unattached EBS Volumes\n")
		for i, vol := range vols {
			sb.WriteString(fmt.Sprintf("resource \"aws_ebs_volume\" \"ghost_volume_%d\" {\n", i))
			sb.WriteString(fmt.Sprintf("  volume_id = \"%s\"\n", vol.ID))
			sb.WriteString("}\n\n")
		}
	}

	// Generate Elastic IPs
	if eips, ok := resourcesByType["eip"]; ok && len(eips) > 0 {
		sb.WriteString("# Unattached Elastic IPs\n")
		for i, eip := range eips {
			sb.WriteString(fmt.Sprintf("resource \"aws_eip\" \"ghost_eip_%d\" {\n", i))
			sb.WriteString(fmt.Sprintf("  allocation_id = \"%s\"\n", eip.ID))
			sb.WriteString("}\n\n")
		}
	}

	// Generate NAT Gateways
	if nats, ok := resourcesByType["nat"]; ok && len(nats) > 0 {
		sb.WriteString("# Unused NAT Gateways\n")
		for i, nat := range nats {
			sb.WriteString(fmt.Sprintf("resource \"aws_nat_gateway\" \"ghost_nat_%d\" {\n", i))
			sb.WriteString(fmt.Sprintf("  nat_gateway_id = \"%s\"\n", nat.ID))
			sb.WriteString("}\n\n")
		}
	}

	// Generate Load Balancers
	if lbs, ok := resourcesByType["loadbalancer"]; ok && len(lbs) > 0 {
		sb.WriteString("# Idle Load Balancers\n")
		for i, lb := range lbs {
			if strings.HasPrefix(lb.ID, "arn") {
				// ALB/NLB
				sb.WriteString(fmt.Sprintf("resource \"aws_lb\" \"ghost_lb_%d\" {\n", i))
				sb.WriteString(fmt.Sprintf("  arn = \"%s\"\n", lb.ID))
				sb.WriteString("}\n\n")
			} else {
				// Classic LB
				sb.WriteString(fmt.Sprintf("resource \"aws_elb\" \"ghost_elb_%d\" {\n", i))
				sb.WriteString(fmt.Sprintf("  name = \"%s\"\n", lb.ID))
				sb.WriteString("}\n\n")
			}
		}
	}

	// Generate Snapshots (RDS and EC2)
	if snaps, ok := resourcesByType["snapshot"]; ok && len(snaps) > 0 {
		sb.WriteString("# Old Snapshots\n")
		for i, snap := range snaps {
			if strings.HasPrefix(snap.ID, "rds:") {
				sb.WriteString(fmt.Sprintf("resource \"aws_db_snapshot\" \"ghost_rds_snap_%d\" {\n", i))
				sb.WriteString(fmt.Sprintf("  db_snapshot_identifier = \"%s\"\n", strings.TrimPrefix(snap.ID, "rds:")))
				sb.WriteString("}\n\n")
			} else {
				sb.WriteString(fmt.Sprintf("resource \"aws_ebs_snapshot\" \"ghost_ebs_snap_%d\" {\n", i))
				sb.WriteString(fmt.Sprintf("  snapshot_id = \"%s\"\n", snap.ID))
				sb.WriteString("}\n\n")
			}
		}
	}

	// Generate S3 buckets
	if buckets, ok := resourcesByType["s3"]; ok && len(buckets) > 0 {
		sb.WriteString("# Empty or old S3 buckets\n")
		for i, bucket := range buckets {
			sb.WriteString(fmt.Sprintf("resource \"aws_s3_bucket\" \"ghost_bucket_%d\" {\n", i))
			sb.WriteString(fmt.Sprintf("  bucket = \"%s\"\n", bucket.ID))
			sb.WriteString("}\n\n")
		}
	}

	// Generate CloudFront distributions
	if dists, ok := resourcesByType["cloudfront"]; ok && len(dists) > 0 {
		sb.WriteString("# Disabled or idle CloudFront distributions\n")
		for i, dist := range dists {
			sb.WriteString(fmt.Sprintf("resource \"aws_cloudfront_distribution\" \"ghost_cf_%d\" {\n", i))
			sb.WriteString(fmt.Sprintf("  id = \"%s\"\n", dist.ID))
			sb.WriteString("}\n\n")
		}
	}

	return sb.String()
}

func generateStateImportCommands(resources []types.Resource) string {
	var sb strings.Builder

	sb.WriteString("\n# Terraform state import commands\n")
	sb.WriteString("# Run these to import existing resources into Terraform state\n")
	sb.WriteString("# Use with caution and verify each import\n\n")

	// Group resources by type
	resourcesByType := make(map[string][]types.Resource)
	for _, r := range resources {
		resourcesByType[r.Type] = append(resourcesByType[r.Type], r)
	}

	// EBS volumes
	if vols, ok := resourcesByType["ebs"]; ok && len(vols) > 0 {
		for i, vol := range vols {
			sb.WriteString(fmt.Sprintf("terraform import aws_ebs_volume.ghost_volume_%d %s\n", i, vol.ID))
		}
	}

	// Elastic IPs
	if eips, ok := resourcesByType["eip"]; ok && len(eips) > 0 {
		for i, eip := range eips {
			sb.WriteString(fmt.Sprintf("terraform import aws_eip.ghost_eip_%d %s\n", i, eip.ID))
		}
	}

	// NAT Gateways
	if nats, ok := resourcesByType["nat"]; ok && len(nats) > 0 {
		for i, nat := range nats {
			sb.WriteString(fmt.Sprintf("terraform import aws_nat_gateway.ghost_nat_%d %s\n", i, nat.ID))
		}
	}

	// Load Balancers
	if lbs, ok := resourcesByType["loadbalancer"]; ok && len(lbs) > 0 {
		for i, lb := range lbs {
			if strings.HasPrefix(lb.ID, "arn") {
				sb.WriteString(fmt.Sprintf("terraform import aws_lb.ghost_lb_%d %s\n", i, lb.ID))
			} else {
				sb.WriteString(fmt.Sprintf("terraform import aws_elb.ghost_elb_%d %s\n", i, lb.ID))
			}
		}
	}

	return sb.String()
}

func writeToFile(filename string, content string) error {
	return os.WriteFile(filename, []byte(content), 0644)
}
